### PR TITLE
Professor Polling Question UI

### PR DESCRIPTION
**Pull request by ZachPeterson**
Added the UI for professors to control the presentation of polling questions to the students.

### CODE REVIEW

**Review by neilgoel — COMMENTED** [review]
I cannot see any of the added UI. I made a lecture with a single question, went live, and nothing shows up for the questions section.

**Comment by ZachPeterson** [comment]
Are you getting any errors in the web console or in Flask? On my machine, if I create a new lecture as the professor with polling questions, I see the question UI when I go live.

**Comment by neilgoel** [comment]
Yeah, getting this on the console
http://localhost:5000/live_lecture/questions/get/NaN Failed to load resource: the server responded with a status of 404 (NOT FOUND)
I'm making a new class, lecture, adding a question, and then going live.

**Comment by ZachPeterson** [comment]
That's called when the live view controller initializes and requests the list of polling questions. It's set with an ng-init near the top of the page source, what values are getting passed into init()? And is there anything in the Flask log from requesting the live lecture page?

**Comment by neilgoel** [comment]
These are all the requests being made
127.0.0.1 - - [24/Nov/2016 01:50:04] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:12] "POST /loginUser HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:12] "GET /getClassList HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:12] "GET /is_student HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:12] "GET /user_id HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /live_lecture/get/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /is_student HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /user_id HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /live_lecture/pace/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /live_lecture/depth/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:14] "GET /live_lecture/questions/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:17] "GET /lectureList/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:17] "GET /get_lecture_list/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:17] "GET /is_student HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:17] "GET /user_id HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:18] "GET /live_lecture/create/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:18] "GET /live_lecture/get/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:18] "GET /is_student HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:19] "GET /user_id HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:19] "GET /live_lecture/pace/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:19] "GET /live_lecture/depth/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:19] "GET /live_lecture/questions/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /live_lecture/create/2 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /live_lecture/get/1 HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /is_student HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /user_id HTTP/1.1" 200 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /live_lecture/pace/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /live_lecture/depth/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:22] "GET /live_lecture/questions/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:25] "GET /static/css/bootstrap.css.map HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:33] "GET /live_lecture/pace/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:33] "GET /live_lecture/depth/get/NaN HTTP/1.1" 404 -
127.0.0.1 - - [24/Nov/2016 01:50:33] "GET /live_lecture/questions/get/NaN HTTP/1.1" 404
Seems to be NaN for quite a few of them

**Comment by ZachPeterson** [comment]
Yeah, looks like something got messed up when Flask tried to build the view. Can you put a breakpoint in get_live_lecture() in Lecture.py and see what is getting passed in for lecture_id and live_lecture_id to the template? It should match what's in the db for your newly created lecture and live lecture. If both of those look good, then check the rendered html file and make sure the values passed into init() match what was in Flask. Even downloading my branch as a zip and running it fresh from there, I'm still not able to get this to reproduce.

**Comment by neilgoel** [comment]
Seems to just mess up on the very first time you the page. After refreshing it works now.

**Review by neilgoel — APPROVED** [review]

**Review by krabagobanjo — CHANGES_REQUESTED** [review]
So I found an interesting issue - when I add a polling question using the UI, the answer shows up as whatever the actual answer is rather than the letter.  As a result, when the lecture with the question is presented the correct answer is not highlighted (even though the pre-added questions work just fine).  I suspect this is just a small change in how polling questions are added.

I found nothing else.

**Comment by ZachPeterson** [comment]
Updated the polling question view to submit the correct answer as 'A', 'B', 'C', or 'D' per the design. The live view should now correctly identify the correct answers as a result.

**Review by neilgoel — COMMENTED** [review]
Can you double check to make sure the stop presenting question button works correctly with updating the database?

**Review by krabagobanjo — APPROVED** [review]

**Comment by ZachPeterson** [comment]
Looks like the API wasn't updating the polling question id in the live lecture, updated it so that field gets nulled out when stopping a polling question

**Pull request merged**
